name: Deploy Github Pages

on:
  push:
    branches:
      - main
  
jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install and build
        run: |
          cd web
          npm install
          npm run build
          cd ..
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: web/dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
