name: Testing

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  gcc-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gcc-version: [ 'gcc:7', 'gcc:8', 'gcc:9', 'gcc:10' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          python -m pip install .[testing]
      - name: Run tests with ${{ matrix.gcc-version }}
        run: |
          export PATH=tests/:$PATH
          export GCC_IMAGE=${{ matrix.gcc-version }}
          g++ --version
          python --version
          pytest
  python-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install .[testing]
      - name: Run tests with Python ${{ matrix.python-version }}
        run: |
          g++ --version
          python --version
          pytest
      - name: Run flake8
        if: ${{ matrix.python-version == '3.9' }}
        run: flake8
  web-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and build
        run: |
          cd web
          npm install
          npm run lint-test
          npm run build
  publish-python-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build
        run: |
          python setup.py dists
          twine check dist/*
  publish-conan-test:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc10
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          conan create .conan
